-- MySQL Script generated by MySQL Workbench
-- Thu 27 Feb 2020 08:29:24 AM GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `writer` VARCHAR(45) NULL,
  `date_published` VARCHAR(100) NULL,
  `cover` VARCHAR(100) NULL,
  `summary` VARCHAR(10000) NULL,
  PRIMARY KEY (`_id`))
ENGINE = MEMORY;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`books`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`books` (`_id`, `name`, `writer`, `date_published`, `cover`, `summary`) VALUES (1, 'Black Company', 'Glen Cook', '454896000', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/97/The_Black_Company.jpg/220px-The_Black_Company.jpg');
INSERT INTO `mydb`.`books` (`_id`, `name`, `writer`, `date_published`, `cover`, `summary`) VALUES (2, 'Black Company Shadows Linger', 'Glen Cook', '465433200', 'https://images-na.ssl-images-amazon.com/images/I/51In8kfvluL._SX307_BO1,204,203,200_.jpg');
INSERT INTO `mydb`.`books` (`_id`, `name`, `writer`, `date_published`, `cover`, `summary`) VALUES (3, 'Black Company The White Rose', 'Glen Cook', '481158000', 'https://images-na.ssl-images-amazon.com/images/I/61bHDPcN5sL._SX304_BO1,204,203,200_.jpg');
INSERT INTO `mydb`.`books` (`_id`, `name`, `writer`, `date_published`, `cover`, `summary`) VALUES (4, 'Common Sense', 'Thomas Paine', '-6108911925', 'https://images-na.ssl-images-amazon.com/images/I/41zVBk2NjUL.jpg');
INSERT INTO `mydb`.`books` (`_id`, `name`, `writer`, `date_published`, `cover`, `summary`) VALUES (5, 'Starship Troopers', 'Robert A. Heinlein', '-320889600', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1304018517l/573833.jpg');

COMMIT;

